name: Tests

on:
  pull_request:
    types:
      - ready_for_review
      - review_requested
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      
      - run: go test ./...